package pkgname

import (
	"database/sql"
	uuid "github.com/google/uuid"
	null "github.com/guregu/null"
	"time"
)

// Code generated by github.com/kmtym1998/chair. DO NOT EDIT.

// character_types:
type CharacterType struct {
	// character_types.id
	ID int

	// character_types.character_value_nullable
	CharacterValueNullable sql.NullString

	// character_types.character_varying_value_nullable
	CharacterVaryingValueNullable sql.NullString

	// character_types.text_value_nullable
	TextValueNullable sql.NullString

	// character_types.character_value
	CharacterValue string

	// character_types.character_varying_value
	CharacterVaryingValue string

	// character_types.text_value
	TextValue string
}

// numeric_types: numeric types
type NumericType struct {
	// numeric_types.id
	ID int

	// numeric_types.smallint_value_nullable: smallint value nullable
	SmallintValueNullable sql.NullInt32

	// numeric_types.integer_value_nullable: integer value nullable
	IntegerValueNullable sql.NullInt32

	// numeric_types.bigint_value_nullable
	BigintValueNullable sql.NullInt64

	// numeric_types.decimal_value_nullable
	DecimalValueNullable sql.NullFloat64

	// numeric_types.numeric_value_nullable
	NumericValueNullable sql.NullFloat64

	// numeric_types.real_value_nullable
	RealValueNullable sql.NullFloat64

	// numeric_types.double_precision_value_nullable
	DoublePrecisionValueNullable sql.NullFloat64

	// numeric_types.smallint_value
	SmallintValue int

	// numeric_types.integer_value
	IntegerValue int

	// numeric_types.bigint_value
	BigintValue int64

	// numeric_types.decimal_value
	DecimalValue float64

	// numeric_types.numeric_value
	NumericValue float64

	// numeric_types.real_value
	RealValue float32

	// numeric_types.double_precision_value
	DoublePrecisionValue float64

	// numeric_types.smallserial_value
	SmallserialValue int

	// numeric_types.serial_value
	SerialValue int

	// numeric_types.bigserial_value
	BigserialValue int64
}

// datetime_types:
type DatetimeType struct {
	// datetime_types.id
	ID int

	// datetime_types.date_value_nullable
	DateValueNullable sql.NullTime

	// datetime_types.time_value_nullable
	TimeValueNullable sql.NullTime

	// datetime_types.timestamp_value_nullable
	TimestampValueNullable null.Time

	// datetime_types.timestamptz_value_nullable
	TimestamptzValueNullable sql.NullTime

	// datetime_types.interval_value_nullable
	IntervalValueNullable interface{}

	// datetime_types.date_value
	DateValue time.Time

	// datetime_types.time_value
	TimeValue time.Time

	// datetime_types.timestamp_value
	TimestampValue time.Time

	// datetime_types.timestamptz_value
	TimestamptzValue time.Time

	// datetime_types.interval_value
	IntervalValue interface{}
}

// uuid_types:
type UUIDType struct {
	// uuid_types.id
	ID int

	// uuid_types.uuid_value_nullable
	UUIDValueNullable sql.NullString

	// uuid_types.uuid_value
	UUIDValue uuid.UUID
}

// money_types:
type MoneyType struct {
	// money_types.id
	ID int

	// money_types.money_value_nullable
	MoneyValueNullable sql.NullFloat64

	// money_types.money_value
	MoneyValue float64
}

// boolean_types:
type BooleanType struct {
	// boolean_types.id
	ID int

	// boolean_types.boolean_value_nullable
	BooleanValueNullable sql.NullBool

	// boolean_types.boolean_value
	BooleanValue bool
}
